### ISSUE TITLE
Upgrade elm-css?

### ISSUE THREAD

**Issue by JuanCaicedo** [abadi199/datetimepicker-css#1]
This project uses `rtfeldman/elm-css` `8.0.0 <= v < 9.0.0`. This is a pretty old version. It would be nice to be able to use it with the latest `elm-css`.

I'm going to try pulling in the code and upgrading. I can submit a PR back if you're interested 😀. It seems pretty difficult to keep publishing new versions here for any `elm-css` update, but maybe there's no way to avoid that?

**Comment by abadi199** [comment]
There's actually a PR for this already on the datetimepicker repo (https://github.com/abadi199/datetimepicker/pull/36). If you want to redo that PR here, it will be awesome.

**Comment by JuanCaicedo** [comment]
Sure, I'll take a look at it and post comments there!

**Comment by abadi199** [comment]
Fixed by #2
